name: Build WebSSH

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉代码
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 安装 Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. 安装 pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 4. 前端构建（webssh）
      - name: Build webssh
        run: |
          cd webssh
          pnpm install
          npm run buildOnly

      # 5. 清空 gossh/webroot 并复制 dist
      - name: Prepare webroot
        run: |
          rm -rf gossh/webroot/*
          cp -r webssh/dist/* gossh/webroot/

      # 6. 安装 Go
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      # 7. 构建 Go
      - name: Build Go binary
        run: |
          cd gossh

          export CGO_ENABLED=0
          export GOOS=linux
          export GOARCH=arm64

          go env -w GOPROXY=https://goproxy.cn,direct
          go mod tidy

          BUILD_TIME=$(date +%Y%m%d_%H%M%S)

          go build -trimpath -ldflags="-s -w" -o webssh_${BUILD_TIME}

      # 8. 安装 UPX
      - name: Install UPX
        run: sudo apt-get install -y upx-ucl

      # 9. 压缩二进制
      - name: Compress binary
        run: |
          cd gossh
          upx --best --lzma webssh_*

      # 10. 上传产物
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: webssh-build
          path: gossh/webssh_*